### ISSUE TITLE
Using methods in the Controller

### ISSUE THREAD

**Issue by Cris123m** [rmunate/PHP2JS#42]
Using version ^4.3 for rmunate/php2js
Laravel 10
PHP 8.2

I want to use the methods to send them to view, according to the documentation, but I cannot access them since I get that the method is not defined.
Should I add or import anything else in the Controller?

```php
class YourController extends Controller
{
    public function index()
    {
        return view('welcome')->with([
            'moonLandingDate' => '1969-07-20'
        ])->toJS();
    }
}
```

**Comment by rmunate** [comment]
# Hello!

We have reviewed the project and found no errors. However, we recommend following these steps to ensure a smooth experience:

## Composer Configuration

Make sure that your `composer.json` file is configured with the latest version. You can check and update the version by running the following command:

```bash
composer require rmunate/php2js "^4.3"
```

This will ensure that you are using the latest version of dependencies.

## Clear Cache

If you experience issues related to the cache, we recommend running the following command to avoid potential conflicts:

```bash
php artisan optimize:clear
```

This command will clear the cache and optimize your application for optimal performance.
