### ISSUE TITLE
Inconsistent PHP Version Requirement in composer.json

### ISSUE THREAD

**Issue by GoodWave2020** [rmunate/PHP2JS#44]
# Description
There is an inconsistency in the composer.json file regarding the PHP version requirement for the illuminate/support package.

# Details
In the current composer.json file, the PHP version requirement is specified as ^8.0, and the illuminate/support package version is specified as ^10.0|^11.0:
https://github.com/rmunate/PHP2JS/blob/master/composer.json#L27-L28

However, the illuminate/support package versions 10.0 and 11.0 require PHP 8.1 or higher. This creates a conflict when trying to install the dependencies with PHP 8.0, as the illuminate/support package cannot be installed due to the unmet PHP version requirement.
https://packagist.org/packages/illuminate/support#v10.0.3

# Proposed Solutions
1. Update the PHP version to 8.1 or higher:
Update the PHP version requirement in the composer.json file to match the illuminate/support package requirement.

```
"require": {
    "php": "^8.1",
    "illuminate/support": "^10.0|^11.0"
}
```

2. Downgrade the illuminate/support package version:
If it is necessary to support PHP 8.0, downgrade the illuminate/support package to a version that supports PHP 8.0.

```
"require": {
    "php": "^8.0",
    "illuminate/support": "^9.0"
}
```

This issue needs to be addressed to ensure that the dependencies can be installed without conflicts and the project can run smoothly with the specified PHP version.

**Comment by GoodWave2020** [comment]
Can I fix it?

I want to choose the first solution.

```
"require": {
    "php": "^8.1",
    "illuminate/support": "^10.0|^11.0"
}
```

**Comment by rmunate** [comment]
Hello, of course, proceed with the PR to approve it

**Comment by GoodWave2020** [comment]
@rmunate 
Hi, Ive created the PR. Could you please review it? Thanks!
